cmake_minimum_required(VERSION 4.0)
project(competitive_programming_2025)

set(CMAKE_CXX_STANDARD 20)

add_executable(competitive_programming_2025 codeforces/young_phisicist.cpp
        codeforces/beautiful_matrix.cpp
        codeforces/queue_school.cpp
        codeforces/borze.cpp
        codeforces/beautiful_year.cpp
        codeforces/word.cpp
        codeforces/word_capitalization.cpp
        codeforces/stones_table.cpp
        codeforces/lights_out.cpp
        codeforces/lucky_number.cpp
        codeforces/boy_girl.cpp
        codeforces/help_math.cpp
        codeforces/petya_strings.cpp
        codeforces/bear_bigbrother.cpp
        codeforces/anton_danik.cpp
        codeforces/elephant.cpp
        contests_pinkballon/A_c3.cpp
        contests_pinkballon/B_c3.cpp
        codeforces/souldier_bananas.cpp
        hackerRank/solveMeFirst.cpp
        codeforces/panoramix.cpp
        leetcode/1480.cpp
        codeforces/chatroom.cpp
        codeforces/stringtask.cpp
        codeforces/petrandbook.cpp
        codeforces/sum.cpp
        codeforces/wrong_subtraction.cpp
        codeforces/translation.cpp
        codeforces/easy_problem.cpp
)
